### ISSUE TITLE
SkyBoxShader won't work with SM4?

### ISSUE THREAD

**Issue by bsambrone** [NemoKradXNA/Randomchaos-MonoGame-Samples#1]
Hello, I LOVE this repo as I'm getting back into monogame! I tried copying your skybox into my OpenGL based monogame project, and the MGCB UI can't seem to build the SkyBoxShader. It tells me that it must be SM 3.0 or lower.

![image](https://user-images.githubusercontent.com/1952115/100528833-e5c96000-3195-11eb-9d8d-34747b0bed81.png)

I've never messed with shaders before, so I naively tried to set it to version 3 and got this and the MGCB UI tells me that TEXCORD0 isn't valid vs_3_0 output semantics:

![image](https://user-images.githubusercontent.com/1952115/100528816-adc21d00-3195-11eb-99a0-70c0ba15c889.png)

What modifications should I make to this shader to have it work for OpenGL monogame projects?

**Comment by NemoKradXNA** [comment]
Hi @bsambrone,

So sorry for me super, super late reply, I never got a notification that you posted here....

Anyway, I'll have a look, see if I can see whats up with it, I am not sure what SM GL supports, never tried it.. 
If nothing else, I can see if I can force it to be SM 3 :)

**Comment by NemoKradXNA** [comment]
@bsambrone, I have a few skybox's in this repo, I just made an alteration to the one in the Terrain sample so it will use OpenGL 2.0

I added this to the top of the shader:-
`#if OPENGL
#define SV_POSITION POSITION
#define VS_SHADERMODEL vs_2_0
#define PS_SHADERMODEL ps_2_0
#else
#define VS_SHADERMODEL vs_4_0_level_9_1
#define PS_SHADERMODEL ps_4_0_level_9_1
#endif`

Then changed the compile in the techniqu like this:-

technique Sky 
{
    pass P0
    {
		FILLMODE = SOLID;
        VertexShader = compile VS_SHADERMODEL Transform();
        PixelShader = compile PS_SHADERMODEL BasicShader();
    }
}

Hope this helps :D
